#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/xiaomi/wayne-common

PRODUCT_COPY_FILES += \
    vendor/xiaomi/wayne-common/proprietary/vendor/etc/acdbdata/MTP/MTP_Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_Bluetooth_cal.acdb \
    vendor/xiaomi/wayne-common/proprietary/vendor/etc/acdbdata/MTP/MTP_General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_General_cal.acdb \
    vendor/xiaomi/wayne-common/proprietary/vendor/etc/acdbdata/MTP/MTP_Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_Global_cal.acdb \
    vendor/xiaomi/wayne-common/proprietary/vendor/etc/acdbdata/MTP/MTP_Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_Handset_cal.acdb \
    vendor/xiaomi/wayne-common/proprietary/vendor/etc/acdbdata/MTP/MTP_Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_Hdmi_cal.acdb \
    vendor/xiaomi/wayne-common/proprietary/vendor/etc/acdbdata/MTP/MTP_Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_Headset_cal.acdb \
    vendor/xiaomi/wayne-common/proprietary/vendor/etc/acdbdata/MTP/MTP_Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_Speaker_cal.acdb \
    vendor/xiaomi/wayne-common/proprietary/vendor/etc/acdbdata/MTP/MTP_workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_workspaceFile.qwsp \
    vendor/xiaomi/wayne-common/proprietary/vendor/etc/acdbdata/adsp_avs_config.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/adsp_avs_config.acdb \
    vendor/xiaomi/wayne-common/proprietary/vendor/etc/camera/camera_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/camera_config.xml \
    vendor/xiaomi/wayne-common/proprietary/vendor/etc/camera/female_bg.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/female_bg.png \
    vendor/xiaomi/wayne-common/proprietary/vendor/etc/camera/female_icon.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/female_icon.png \
    vendor/xiaomi/wayne-common/proprietary/vendor/etc/camera/male_bg.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/male_bg.png \
    vendor/xiaomi/wayne-common/proprietary/vendor/etc/camera/male_icon.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/male_icon.png \
    vendor/xiaomi/wayne-common/proprietary/vendor/etc/camera/score_bg.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/score_bg.png \
    vendor/xiaomi/wayne-common/proprietary/vendor/etc/camera/score_icon.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/score_icon.png \
    vendor/xiaomi/wayne-common/proprietary/vendor/etc/camera/wayne_imx376_ofilm_cn_back_ii_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/wayne_imx376_ofilm_cn_back_ii_chromatix.xml \
    vendor/xiaomi/wayne-common/proprietary/vendor/etc/camera/wayne_imx376_ofilm_cn_front_ii_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/wayne_imx376_ofilm_cn_front_ii_chromatix.xml \
    vendor/xiaomi/wayne-common/proprietary/vendor/etc/camera/wayne_imx376_ofilm_india_back_ii_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/wayne_imx376_ofilm_india_back_ii_chromatix.xml \
    vendor/xiaomi/wayne-common/proprietary/vendor/etc/camera/wayne_imx376_ofilm_india_front_ii_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/wayne_imx376_ofilm_india_front_ii_chromatix.xml \
    vendor/xiaomi/wayne-common/proprietary/vendor/etc/camera/wayne_imx376_sunny_cn_back_i_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/wayne_imx376_sunny_cn_back_i_chromatix.xml \
    vendor/xiaomi/wayne-common/proprietary/vendor/etc/camera/wayne_imx376_sunny_cn_back_iii_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/wayne_imx376_sunny_cn_back_iii_chromatix.xml \
    vendor/xiaomi/wayne-common/proprietary/vendor/etc/camera/wayne_imx376_sunny_cn_front_i_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/wayne_imx376_sunny_cn_front_i_chromatix.xml \
    vendor/xiaomi/wayne-common/proprietary/vendor/etc/camera/wayne_imx376_sunny_india_back_i_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/wayne_imx376_sunny_india_back_i_chromatix.xml \
    vendor/xiaomi/wayne-common/proprietary/vendor/etc/camera/wayne_imx376_sunny_india_back_iii_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/wayne_imx376_sunny_india_back_iii_chromatix.xml \
    vendor/xiaomi/wayne-common/proprietary/vendor/etc/camera/wayne_imx376_sunny_india_front_i_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/wayne_imx376_sunny_india_front_i_chromatix.xml \
    vendor/xiaomi/wayne-common/proprietary/vendor/etc/camera/wayne_imx486_ofilm_cn_ii_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/wayne_imx486_ofilm_cn_ii_chromatix.xml \
    vendor/xiaomi/wayne-common/proprietary/vendor/etc/camera/wayne_imx486_ofilm_india_ii_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/wayne_imx486_ofilm_india_ii_chromatix.xml \
    vendor/xiaomi/wayne-common/proprietary/vendor/etc/camera/wayne_imx486_sunny_cn_i_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/wayne_imx486_sunny_cn_i_chromatix.xml \
    vendor/xiaomi/wayne-common/proprietary/vendor/etc/camera/wayne_imx486_sunny_cn_iii_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/wayne_imx486_sunny_cn_iii_chromatix.xml \
    vendor/xiaomi/wayne-common/proprietary/vendor/etc/camera/wayne_imx486_sunny_india_i_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/wayne_imx486_sunny_india_i_chromatix.xml \
    vendor/xiaomi/wayne-common/proprietary/vendor/etc/camera/wayne_imx486_sunny_india_iii_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/wayne_imx486_sunny_india_iii_chromatix.xml \
    vendor/xiaomi/wayne-common/proprietary/vendor/etc/init/android.hardware.gatekeeper@1.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.gatekeeper@1.0-service-qti.rc \
    vendor/xiaomi/wayne-common/proprietary/vendor/etc/init/android.hardware.keymaster@3.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.keymaster@3.0-service-qti.rc \
    vendor/xiaomi/wayne-common/proprietary/vendor/etc/qdcm_calib_data_jdi_nt36672_fhd_video_mode_dsi_panel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_jdi_nt36672_fhd_video_mode_dsi_panel.xml \
    vendor/xiaomi/wayne-common/proprietary/vendor/etc/qdcm_calib_data_tianma_nt36672_fhd_video_mode_dsi_panel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_tianma_nt36672_fhd_video_mode_dsi_panel.xml \
    vendor/xiaomi/wayne-common/proprietary/vendor/etc/sensors/hals.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/hals.conf \
    vendor/xiaomi/wayne-common/proprietary/vendor/etc/sensors/sensor_def_qcomdev.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/sensor_def_qcomdev.conf \
    vendor/xiaomi/wayne-common/proprietary/vendor/etc/thermal-engine-map.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine-map.conf \
    vendor/xiaomi/wayne-common/proprietary/vendor/etc/thermal-engine-normal.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine-normal.conf \
    vendor/xiaomi/wayne-common/proprietary/vendor/etc/thermal-engine-video.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine-video.conf \
    vendor/xiaomi/wayne-common/proprietary/vendor/etc/thermal-engine.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine.conf \
    vendor/xiaomi/wayne-common/proprietary/vendor/firmware/a512_zap.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/a512_zap.b00 \
    vendor/xiaomi/wayne-common/proprietary/vendor/firmware/a512_zap.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/a512_zap.b01 \
    vendor/xiaomi/wayne-common/proprietary/vendor/firmware/a512_zap.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/a512_zap.b02 \
    vendor/xiaomi/wayne-common/proprietary/vendor/firmware/a512_zap.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/a512_zap.elf \
    vendor/xiaomi/wayne-common/proprietary/vendor/firmware/a512_zap.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/a512_zap.mdt \
    vendor/xiaomi/wayne-common/proprietary/vendor/firmware/a530_pfp.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_pfp.fw \
    vendor/xiaomi/wayne-common/proprietary/vendor/firmware/a530_pm4.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_pm4.fw \
    vendor/xiaomi/wayne-common/proprietary/vendor/firmware/a540_gpmu.fw2:$(TARGET_COPY_OUT_VENDOR)/firmware/a540_gpmu.fw2 \
    vendor/xiaomi/wayne-common/proprietary/vendor/firmware/cpp_firmware_v1_12_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_12_0.fw \
    vendor/xiaomi/wayne-common/proprietary/vendor/firmware/dbmd4_va_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/dbmd4_va_fw.bin \
    vendor/xiaomi/wayne-common/proprietary/vendor/firmware/fpctzappfingerprint.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/fpctzappfingerprint.b00 \
    vendor/xiaomi/wayne-common/proprietary/vendor/firmware/fpctzappfingerprint.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/fpctzappfingerprint.b01 \
    vendor/xiaomi/wayne-common/proprietary/vendor/firmware/fpctzappfingerprint.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/fpctzappfingerprint.b02 \
    vendor/xiaomi/wayne-common/proprietary/vendor/firmware/fpctzappfingerprint.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/fpctzappfingerprint.b03 \
    vendor/xiaomi/wayne-common/proprietary/vendor/firmware/fpctzappfingerprint.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/fpctzappfingerprint.b04 \
    vendor/xiaomi/wayne-common/proprietary/vendor/firmware/fpctzappfingerprint.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/fpctzappfingerprint.b05 \
    vendor/xiaomi/wayne-common/proprietary/vendor/firmware/fpctzappfingerprint.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/fpctzappfingerprint.b06 \
    vendor/xiaomi/wayne-common/proprietary/vendor/firmware/fpctzappfingerprint.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/fpctzappfingerprint.b07 \
    vendor/xiaomi/wayne-common/proprietary/vendor/firmware/fpctzappfingerprint.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/fpctzappfingerprint.mdt \
    vendor/xiaomi/wayne-common/proprietary/vendor/firmware/goodixfp.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/goodixfp.b00 \
    vendor/xiaomi/wayne-common/proprietary/vendor/firmware/goodixfp.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/goodixfp.b01 \
    vendor/xiaomi/wayne-common/proprietary/vendor/firmware/goodixfp.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/goodixfp.b02 \
    vendor/xiaomi/wayne-common/proprietary/vendor/firmware/goodixfp.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/goodixfp.b03 \
    vendor/xiaomi/wayne-common/proprietary/vendor/firmware/goodixfp.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/goodixfp.b04 \
    vendor/xiaomi/wayne-common/proprietary/vendor/firmware/goodixfp.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/goodixfp.b05 \
    vendor/xiaomi/wayne-common/proprietary/vendor/firmware/goodixfp.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/goodixfp.b06 \
    vendor/xiaomi/wayne-common/proprietary/vendor/firmware/goodixfp.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/goodixfp.b07 \
    vendor/xiaomi/wayne-common/proprietary/vendor/firmware/goodixfp.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/goodixfp.mdt \
    vendor/xiaomi/wayne-common/proprietary/vendor/firmware/tas2557_uCDSP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/tas2557_uCDSP.bin \
    vendor/xiaomi/wayne-common/proprietary/vendor/firmware/tfa98xx.cnt:$(TARGET_COPY_OUT_VENDOR)/firmware/tfa98xx.cnt \
    vendor/xiaomi/wayne-common/proprietary/vendor/lib/mibokeh_660_opencl.bin:$(TARGET_COPY_OUT_VENDOR)/lib/mibokeh_660_opencl.bin

PRODUCT_PACKAGES += \
    android.hardware.gatekeeper@1.0-impl-qti \
    android.hardware.keymaster@3.0-impl-qti \
    libmmcamera2_frame_algorithm \
    libmmcamera2_is \
    libmmcamera2_q3a_core \
    libmmcamera2_stats_algorithm \
    libmmcamera2_stats_lib \
    libmmcamera_dbg \
    libmmcamera_faceproc \
    libmmcamera_faceproc2 \
    libmmcamera_tintless_algo \
    libmmcamera_tintless_bg_pca_algo \
    libsensor1 \
    libsensor_reg \
    libthermalclient \
    libvideoutils \
    sensors.ssc \
    camera.sdm660 \
    libMiWatermark \
    libSonyIMX376C3RmscLibrary \
    libSonyIMX376KRmscLibrary \
    libXMFD_AgeGender \
    lib_lowlight \
    libactuator_wayne_imx376_ofilm_back_ii_dw9763 \
    libactuator_wayne_imx376_sunny_back_i_dw9763 \
    libactuator_wayne_imx486_ofilm_ii_dw9763 \
    libactuator_wayne_imx486_sunny_i_dw9763 \
    libadsp_hvx_callback_skel \
    libadsp_hvx_stub \
    libarcsoft_beautyshot \
    libarcsoft_dualcam_refocus \
    libarcsoft_dualcam_refocus_rear_t \
    libarcsoft_dualcam_refocus_rear_w \
    libarcsoft_high_dynamic_range \
    libchromatix_wayne_imx376_ofilm_cn_back_ii_bokeh_preview \
    libchromatix_wayne_imx376_ofilm_cn_back_ii_bokeh_preview_3a \
    libchromatix_wayne_imx376_ofilm_cn_back_ii_common \
    libchromatix_wayne_imx376_ofilm_cn_back_ii_cpp_hfr_120 \
    libchromatix_wayne_imx376_ofilm_cn_back_ii_cpp_liveshot \
    libchromatix_wayne_imx376_ofilm_cn_back_ii_cpp_preview \
    libchromatix_wayne_imx376_ofilm_cn_back_ii_cpp_snapshot \
    libchromatix_wayne_imx376_ofilm_cn_back_ii_cpp_snapshot_5M \
    libchromatix_wayne_imx376_ofilm_cn_back_ii_cpp_snapshot_5M_hht \
    libchromatix_wayne_imx376_ofilm_cn_back_ii_cpp_snapshot_bokeh \
    libchromatix_wayne_imx376_ofilm_cn_back_ii_cpp_snapshot_downscale \
    libchromatix_wayne_imx376_ofilm_cn_back_ii_cpp_snapshot_hht \
    libchromatix_wayne_imx376_ofilm_cn_back_ii_cpp_snapshot_upscale \
    libchromatix_wayne_imx376_ofilm_cn_back_ii_cpp_video \
    libchromatix_wayne_imx376_ofilm_cn_back_ii_cpp_video_default \
    libchromatix_wayne_imx376_ofilm_cn_back_ii_cpp_video_weixin \
    libchromatix_wayne_imx376_ofilm_cn_back_ii_default_preview_3a \
    libchromatix_wayne_imx376_ofilm_cn_back_ii_default_video_3a \
    libchromatix_wayne_imx376_ofilm_cn_back_ii_flash_preview_3a \
    libchromatix_wayne_imx376_ofilm_cn_back_ii_flash_video_3a \
    libchromatix_wayne_imx376_ofilm_cn_back_ii_fullsize_preview_3a \
    libchromatix_wayne_imx376_ofilm_cn_back_ii_fullsize_video_3a \
    libchromatix_wayne_imx376_ofilm_cn_back_ii_hfr_120 \
    libchromatix_wayne_imx376_ofilm_cn_back_ii_hfr_120_3a \
    libchromatix_wayne_imx376_ofilm_cn_back_ii_postproc \
    libchromatix_wayne_imx376_ofilm_cn_back_ii_preview \
    libchromatix_wayne_imx376_ofilm_cn_back_ii_snapshot \
    libchromatix_wayne_imx376_ofilm_cn_back_ii_video_default \
    libchromatix_wayne_imx376_ofilm_cn_back_ii_video_weixin \
    libchromatix_wayne_imx376_ofilm_cn_back_ii_weixin_video_3a \
    libchromatix_wayne_imx376_ofilm_cn_front_ii_common \
    libchromatix_wayne_imx376_ofilm_cn_front_ii_cpp_liveshot \
    libchromatix_wayne_imx376_ofilm_cn_front_ii_cpp_preview \
    libchromatix_wayne_imx376_ofilm_cn_front_ii_cpp_snapshot \
    libchromatix_wayne_imx376_ofilm_cn_front_ii_cpp_snapshot_5M \
    libchromatix_wayne_imx376_ofilm_cn_front_ii_cpp_snapshot_5M_hht \
    libchromatix_wayne_imx376_ofilm_cn_front_ii_cpp_snapshot_downscale \
    libchromatix_wayne_imx376_ofilm_cn_front_ii_cpp_snapshot_hdr \
    libchromatix_wayne_imx376_ofilm_cn_front_ii_cpp_snapshot_hht \
    libchromatix_wayne_imx376_ofilm_cn_front_ii_cpp_snapshot_upscale \
    libchromatix_wayne_imx376_ofilm_cn_front_ii_cpp_video \
    libchromatix_wayne_imx376_ofilm_cn_front_ii_cpp_video_default \
    libchromatix_wayne_imx376_ofilm_cn_front_ii_cpp_video_face \
    libchromatix_wayne_imx376_ofilm_cn_front_ii_cpp_video_weixin \
    libchromatix_wayne_imx376_ofilm_cn_front_ii_default_preview_3a \
    libchromatix_wayne_imx376_ofilm_cn_front_ii_default_video_3a \
    libchromatix_wayne_imx376_ofilm_cn_front_ii_face_video_3a \
    libchromatix_wayne_imx376_ofilm_cn_front_ii_flash_cpp_liveshot \
    libchromatix_wayne_imx376_ofilm_cn_front_ii_flash_cpp_preview \
    libchromatix_wayne_imx376_ofilm_cn_front_ii_flash_cpp_snapshot \
    libchromatix_wayne_imx376_ofilm_cn_front_ii_flash_cpp_video \
    libchromatix_wayne_imx376_ofilm_cn_front_ii_flash_preview \
    libchromatix_wayne_imx376_ofilm_cn_front_ii_flash_preview_3a \
    libchromatix_wayne_imx376_ofilm_cn_front_ii_flash_snapshot \
    libchromatix_wayne_imx376_ofilm_cn_front_ii_flash_video \
    libchromatix_wayne_imx376_ofilm_cn_front_ii_flash_video_3a \
    libchromatix_wayne_imx376_ofilm_cn_front_ii_fullsize_preview_3a \
    libchromatix_wayne_imx376_ofilm_cn_front_ii_fullsize_video_3a \
    libchromatix_wayne_imx376_ofilm_cn_front_ii_postproc \
    libchromatix_wayne_imx376_ofilm_cn_front_ii_preview \
    libchromatix_wayne_imx376_ofilm_cn_front_ii_snapshot \
    libchromatix_wayne_imx376_ofilm_cn_front_ii_snapshot_hdr \
    libchromatix_wayne_imx376_ofilm_cn_front_ii_video_default \
    libchromatix_wayne_imx376_ofilm_cn_front_ii_video_face \
    libchromatix_wayne_imx376_ofilm_cn_front_ii_video_weixin \
    libchromatix_wayne_imx376_ofilm_cn_front_ii_weixin_video_3a \
    libchromatix_wayne_imx376_ofilm_india_back_ii_bokeh_preview \
    libchromatix_wayne_imx376_ofilm_india_back_ii_bokeh_preview_3a \
    libchromatix_wayne_imx376_ofilm_india_back_ii_common \
    libchromatix_wayne_imx376_ofilm_india_back_ii_cpp_liveshot \
    libchromatix_wayne_imx376_ofilm_india_back_ii_cpp_preview \
    libchromatix_wayne_imx376_ofilm_india_back_ii_cpp_snapshot \
    libchromatix_wayne_imx376_ofilm_india_back_ii_cpp_snapshot_5M \
    libchromatix_wayne_imx376_ofilm_india_back_ii_cpp_snapshot_5M_hht \
    libchromatix_wayne_imx376_ofilm_india_back_ii_cpp_snapshot_bokeh \
    libchromatix_wayne_imx376_ofilm_india_back_ii_cpp_snapshot_downscale \
    libchromatix_wayne_imx376_ofilm_india_back_ii_cpp_snapshot_hht \
    libchromatix_wayne_imx376_ofilm_india_back_ii_cpp_snapshot_upscale \
    libchromatix_wayne_imx376_ofilm_india_back_ii_cpp_video \
    libchromatix_wayne_imx376_ofilm_india_back_ii_cpp_video_default \
    libchromatix_wayne_imx376_ofilm_india_back_ii_cpp_video_weixin \
    libchromatix_wayne_imx376_ofilm_india_back_ii_default_preview_3a \
    libchromatix_wayne_imx376_ofilm_india_back_ii_default_video_3a \
    libchromatix_wayne_imx376_ofilm_india_back_ii_flash_preview_3a \
    libchromatix_wayne_imx376_ofilm_india_back_ii_flash_video_3a \
    libchromatix_wayne_imx376_ofilm_india_back_ii_fullsize_preview_3a \
    libchromatix_wayne_imx376_ofilm_india_back_ii_fullsize_video_3a \
    libchromatix_wayne_imx376_ofilm_india_back_ii_postproc \
    libchromatix_wayne_imx376_ofilm_india_back_ii_preview \
    libchromatix_wayne_imx376_ofilm_india_back_ii_snapshot \
    libchromatix_wayne_imx376_ofilm_india_back_ii_video_default \
    libchromatix_wayne_imx376_ofilm_india_back_ii_video_weixin \
    libchromatix_wayne_imx376_ofilm_india_back_ii_weixin_video_3a \
    libchromatix_wayne_imx376_ofilm_india_front_ii_common \
    libchromatix_wayne_imx376_ofilm_india_front_ii_cpp_liveshot \
    libchromatix_wayne_imx376_ofilm_india_front_ii_cpp_preview \
    libchromatix_wayne_imx376_ofilm_india_front_ii_cpp_snapshot \
    libchromatix_wayne_imx376_ofilm_india_front_ii_cpp_snapshot_5M \
    libchromatix_wayne_imx376_ofilm_india_front_ii_cpp_snapshot_5M_hht \
    libchromatix_wayne_imx376_ofilm_india_front_ii_cpp_snapshot_downscale \
    libchromatix_wayne_imx376_ofilm_india_front_ii_cpp_snapshot_hdr \
    libchromatix_wayne_imx376_ofilm_india_front_ii_cpp_snapshot_hht \
    libchromatix_wayne_imx376_ofilm_india_front_ii_cpp_snapshot_upscale \
    libchromatix_wayne_imx376_ofilm_india_front_ii_cpp_video \
    libchromatix_wayne_imx376_ofilm_india_front_ii_cpp_video_default \
    libchromatix_wayne_imx376_ofilm_india_front_ii_cpp_video_face \
    libchromatix_wayne_imx376_ofilm_india_front_ii_cpp_video_weixin \
    libchromatix_wayne_imx376_ofilm_india_front_ii_default_preview_3a \
    libchromatix_wayne_imx376_ofilm_india_front_ii_default_video_3a \
    libchromatix_wayne_imx376_ofilm_india_front_ii_face_video_3a \
    libchromatix_wayne_imx376_ofilm_india_front_ii_flash_cpp_liveshot \
    libchromatix_wayne_imx376_ofilm_india_front_ii_flash_cpp_preview \
    libchromatix_wayne_imx376_ofilm_india_front_ii_flash_cpp_snapshot \
    libchromatix_wayne_imx376_ofilm_india_front_ii_flash_cpp_video \
    libchromatix_wayne_imx376_ofilm_india_front_ii_flash_preview \
    libchromatix_wayne_imx376_ofilm_india_front_ii_flash_preview_3a \
    libchromatix_wayne_imx376_ofilm_india_front_ii_flash_snapshot \
    libchromatix_wayne_imx376_ofilm_india_front_ii_flash_video \
    libchromatix_wayne_imx376_ofilm_india_front_ii_flash_video_3a \
    libchromatix_wayne_imx376_ofilm_india_front_ii_fullsize_preview_3a \
    libchromatix_wayne_imx376_ofilm_india_front_ii_fullsize_video_3a \
    libchromatix_wayne_imx376_ofilm_india_front_ii_postproc \
    libchromatix_wayne_imx376_ofilm_india_front_ii_preview \
    libchromatix_wayne_imx376_ofilm_india_front_ii_snapshot \
    libchromatix_wayne_imx376_ofilm_india_front_ii_snapshot_hdr \
    libchromatix_wayne_imx376_ofilm_india_front_ii_video_default \
    libchromatix_wayne_imx376_ofilm_india_front_ii_video_face \
    libchromatix_wayne_imx376_ofilm_india_front_ii_video_weixin \
    libchromatix_wayne_imx376_ofilm_india_front_ii_weixin_video_3a \
    libchromatix_wayne_imx376_sunny_cn_back_i_bokeh_preview \
    libchromatix_wayne_imx376_sunny_cn_back_i_bokeh_preview_3a \
    libchromatix_wayne_imx376_sunny_cn_back_i_common \
    libchromatix_wayne_imx376_sunny_cn_back_i_cpp_hfr_120 \
    libchromatix_wayne_imx376_sunny_cn_back_i_cpp_liveshot \
    libchromatix_wayne_imx376_sunny_cn_back_i_cpp_preview \
    libchromatix_wayne_imx376_sunny_cn_back_i_cpp_snapshot \
    libchromatix_wayne_imx376_sunny_cn_back_i_cpp_snapshot_5M \
    libchromatix_wayne_imx376_sunny_cn_back_i_cpp_snapshot_5M_hht \
    libchromatix_wayne_imx376_sunny_cn_back_i_cpp_snapshot_bokeh \
    libchromatix_wayne_imx376_sunny_cn_back_i_cpp_snapshot_downscale \
    libchromatix_wayne_imx376_sunny_cn_back_i_cpp_snapshot_hht \
    libchromatix_wayne_imx376_sunny_cn_back_i_cpp_snapshot_upscale \
    libchromatix_wayne_imx376_sunny_cn_back_i_cpp_video \
    libchromatix_wayne_imx376_sunny_cn_back_i_cpp_video_default \
    libchromatix_wayne_imx376_sunny_cn_back_i_cpp_video_weixin \
    libchromatix_wayne_imx376_sunny_cn_back_i_default_preview_3a \
    libchromatix_wayne_imx376_sunny_cn_back_i_default_video_3a \
    libchromatix_wayne_imx376_sunny_cn_back_i_flash_preview_3a \
    libchromatix_wayne_imx376_sunny_cn_back_i_flash_video_3a \
    libchromatix_wayne_imx376_sunny_cn_back_i_fullsize_preview_3a \
    libchromatix_wayne_imx376_sunny_cn_back_i_fullsize_video_3a \
    libchromatix_wayne_imx376_sunny_cn_back_i_hfr_120 \
    libchromatix_wayne_imx376_sunny_cn_back_i_hfr_120_3a \
    libchromatix_wayne_imx376_sunny_cn_back_i_postproc \
    libchromatix_wayne_imx376_sunny_cn_back_i_preview \
    libchromatix_wayne_imx376_sunny_cn_back_i_snapshot \
    libchromatix_wayne_imx376_sunny_cn_back_i_video_default \
    libchromatix_wayne_imx376_sunny_cn_back_i_video_weixin \
    libchromatix_wayne_imx376_sunny_cn_back_i_weixin_video_3a \
    libchromatix_wayne_imx376_sunny_cn_back_iii_bokeh_preview \
    libchromatix_wayne_imx376_sunny_cn_back_iii_bokeh_preview_3a \
    libchromatix_wayne_imx376_sunny_cn_back_iii_common \
    libchromatix_wayne_imx376_sunny_cn_back_iii_cpp_hfr_120 \
    libchromatix_wayne_imx376_sunny_cn_back_iii_cpp_liveshot \
    libchromatix_wayne_imx376_sunny_cn_back_iii_cpp_preview \
    libchromatix_wayne_imx376_sunny_cn_back_iii_cpp_snapshot \
    libchromatix_wayne_imx376_sunny_cn_back_iii_cpp_snapshot_5M \
    libchromatix_wayne_imx376_sunny_cn_back_iii_cpp_snapshot_5M_hht \
    libchromatix_wayne_imx376_sunny_cn_back_iii_cpp_snapshot_bokeh \
    libchromatix_wayne_imx376_sunny_cn_back_iii_cpp_snapshot_downscale \
    libchromatix_wayne_imx376_sunny_cn_back_iii_cpp_snapshot_hht \
    libchromatix_wayne_imx376_sunny_cn_back_iii_cpp_snapshot_upscale \
    libchromatix_wayne_imx376_sunny_cn_back_iii_cpp_video \
    libchromatix_wayne_imx376_sunny_cn_back_iii_cpp_video_default \
    libchromatix_wayne_imx376_sunny_cn_back_iii_cpp_video_weixin \
    libchromatix_wayne_imx376_sunny_cn_back_iii_default_preview_3a \
    libchromatix_wayne_imx376_sunny_cn_back_iii_default_video_3a \
    libchromatix_wayne_imx376_sunny_cn_back_iii_flash_preview_3a \
    libchromatix_wayne_imx376_sunny_cn_back_iii_flash_video_3a \
    libchromatix_wayne_imx376_sunny_cn_back_iii_fullsize_preview_3a \
    libchromatix_wayne_imx376_sunny_cn_back_iii_fullsize_video_3a \
    libchromatix_wayne_imx376_sunny_cn_back_iii_hfr_120 \
    libchromatix_wayne_imx376_sunny_cn_back_iii_hfr_120_3a \
    libchromatix_wayne_imx376_sunny_cn_back_iii_postproc \
    libchromatix_wayne_imx376_sunny_cn_back_iii_preview \
    libchromatix_wayne_imx376_sunny_cn_back_iii_snapshot \
    libchromatix_wayne_imx376_sunny_cn_back_iii_video_default \
    libchromatix_wayne_imx376_sunny_cn_back_iii_video_weixin \
    libchromatix_wayne_imx376_sunny_cn_back_iii_weixin_video_3a \
    libchromatix_wayne_imx376_sunny_cn_front_i_common \
    libchromatix_wayne_imx376_sunny_cn_front_i_cpp_liveshot \
    libchromatix_wayne_imx376_sunny_cn_front_i_cpp_preview \
    libchromatix_wayne_imx376_sunny_cn_front_i_cpp_snapshot \
    libchromatix_wayne_imx376_sunny_cn_front_i_cpp_snapshot_5M \
    libchromatix_wayne_imx376_sunny_cn_front_i_cpp_snapshot_5M_hht \
    libchromatix_wayne_imx376_sunny_cn_front_i_cpp_snapshot_downscale \
    libchromatix_wayne_imx376_sunny_cn_front_i_cpp_snapshot_hdr \
    libchromatix_wayne_imx376_sunny_cn_front_i_cpp_snapshot_hht \
    libchromatix_wayne_imx376_sunny_cn_front_i_cpp_snapshot_upscale \
    libchromatix_wayne_imx376_sunny_cn_front_i_cpp_video \
    libchromatix_wayne_imx376_sunny_cn_front_i_cpp_video_default \
    libchromatix_wayne_imx376_sunny_cn_front_i_cpp_video_face \
    libchromatix_wayne_imx376_sunny_cn_front_i_cpp_video_weixin \
    libchromatix_wayne_imx376_sunny_cn_front_i_default_preview_3a \
    libchromatix_wayne_imx376_sunny_cn_front_i_default_video_3a \
    libchromatix_wayne_imx376_sunny_cn_front_i_face_video_3a \
    libchromatix_wayne_imx376_sunny_cn_front_i_flash_cpp_liveshot \
    libchromatix_wayne_imx376_sunny_cn_front_i_flash_cpp_preview \
    libchromatix_wayne_imx376_sunny_cn_front_i_flash_cpp_snapshot \
    libchromatix_wayne_imx376_sunny_cn_front_i_flash_cpp_video \
    libchromatix_wayne_imx376_sunny_cn_front_i_flash_preview \
    libchromatix_wayne_imx376_sunny_cn_front_i_flash_preview_3a \
    libchromatix_wayne_imx376_sunny_cn_front_i_flash_snapshot \
    libchromatix_wayne_imx376_sunny_cn_front_i_flash_video \
    libchromatix_wayne_imx376_sunny_cn_front_i_flash_video_3a \
    libchromatix_wayne_imx376_sunny_cn_front_i_fullsize_preview_3a \
    libchromatix_wayne_imx376_sunny_cn_front_i_fullsize_video_3a \
    libchromatix_wayne_imx376_sunny_cn_front_i_postproc \
    libchromatix_wayne_imx376_sunny_cn_front_i_preview \
    libchromatix_wayne_imx376_sunny_cn_front_i_snapshot \
    libchromatix_wayne_imx376_sunny_cn_front_i_snapshot_hdr \
    libchromatix_wayne_imx376_sunny_cn_front_i_video_default \
    libchromatix_wayne_imx376_sunny_cn_front_i_video_face \
    libchromatix_wayne_imx376_sunny_cn_front_i_video_weixin \
    libchromatix_wayne_imx376_sunny_cn_front_i_weixin_video_3a \
    libchromatix_wayne_imx376_sunny_india_back_i_bokeh_preview \
    libchromatix_wayne_imx376_sunny_india_back_i_bokeh_preview_3a \
    libchromatix_wayne_imx376_sunny_india_back_i_common \
    libchromatix_wayne_imx376_sunny_india_back_i_cpp_liveshot \
    libchromatix_wayne_imx376_sunny_india_back_i_cpp_preview \
    libchromatix_wayne_imx376_sunny_india_back_i_cpp_snapshot \
    libchromatix_wayne_imx376_sunny_india_back_i_cpp_snapshot_5M \
    libchromatix_wayne_imx376_sunny_india_back_i_cpp_snapshot_5M_hht \
    libchromatix_wayne_imx376_sunny_india_back_i_cpp_snapshot_bokeh \
    libchromatix_wayne_imx376_sunny_india_back_i_cpp_snapshot_downscale \
    libchromatix_wayne_imx376_sunny_india_back_i_cpp_snapshot_hht \
    libchromatix_wayne_imx376_sunny_india_back_i_cpp_snapshot_upscale \
    libchromatix_wayne_imx376_sunny_india_back_i_cpp_video \
    libchromatix_wayne_imx376_sunny_india_back_i_cpp_video_default \
    libchromatix_wayne_imx376_sunny_india_back_i_cpp_video_weixin \
    libchromatix_wayne_imx376_sunny_india_back_i_default_preview_3a \
    libchromatix_wayne_imx376_sunny_india_back_i_default_video_3a \
    libchromatix_wayne_imx376_sunny_india_back_i_flash_preview_3a \
    libchromatix_wayne_imx376_sunny_india_back_i_flash_video_3a \
    libchromatix_wayne_imx376_sunny_india_back_i_fullsize_preview_3a \
    libchromatix_wayne_imx376_sunny_india_back_i_fullsize_video_3a \
    libchromatix_wayne_imx376_sunny_india_back_i_postproc \
    libchromatix_wayne_imx376_sunny_india_back_i_preview \
    libchromatix_wayne_imx376_sunny_india_back_i_snapshot \
    libchromatix_wayne_imx376_sunny_india_back_i_video_default \
    libchromatix_wayne_imx376_sunny_india_back_i_video_weixin \
    libchromatix_wayne_imx376_sunny_india_back_i_weixin_video_3a \
    libchromatix_wayne_imx376_sunny_india_back_iii_bokeh_preview \
    libchromatix_wayne_imx376_sunny_india_back_iii_bokeh_preview_3a \
    libchromatix_wayne_imx376_sunny_india_back_iii_common \
    libchromatix_wayne_imx376_sunny_india_back_iii_cpp_liveshot \
    libchromatix_wayne_imx376_sunny_india_back_iii_cpp_preview \
    libchromatix_wayne_imx376_sunny_india_back_iii_cpp_snapshot \
    libchromatix_wayne_imx376_sunny_india_back_iii_cpp_snapshot_5M \
    libchromatix_wayne_imx376_sunny_india_back_iii_cpp_snapshot_5M_hht \
    libchromatix_wayne_imx376_sunny_india_back_iii_cpp_snapshot_bokeh \
    libchromatix_wayne_imx376_sunny_india_back_iii_cpp_snapshot_downscale \
    libchromatix_wayne_imx376_sunny_india_back_iii_cpp_snapshot_hht \
    libchromatix_wayne_imx376_sunny_india_back_iii_cpp_snapshot_upscale \
    libchromatix_wayne_imx376_sunny_india_back_iii_cpp_video \
    libchromatix_wayne_imx376_sunny_india_back_iii_cpp_video_default \
    libchromatix_wayne_imx376_sunny_india_back_iii_cpp_video_weixin \
    libchromatix_wayne_imx376_sunny_india_back_iii_default_preview_3a \
    libchromatix_wayne_imx376_sunny_india_back_iii_default_video_3a \
    libchromatix_wayne_imx376_sunny_india_back_iii_flash_preview_3a \
    libchromatix_wayne_imx376_sunny_india_back_iii_flash_video_3a \
    libchromatix_wayne_imx376_sunny_india_back_iii_fullsize_preview_3a \
    libchromatix_wayne_imx376_sunny_india_back_iii_fullsize_video_3a \
    libchromatix_wayne_imx376_sunny_india_back_iii_postproc \
    libchromatix_wayne_imx376_sunny_india_back_iii_preview \
    libchromatix_wayne_imx376_sunny_india_back_iii_snapshot \
    libchromatix_wayne_imx376_sunny_india_back_iii_video_default \
    libchromatix_wayne_imx376_sunny_india_back_iii_video_weixin \
    libchromatix_wayne_imx376_sunny_india_back_iii_weixin_video_3a \
    libchromatix_wayne_imx376_sunny_india_front_i_common \
    libchromatix_wayne_imx376_sunny_india_front_i_cpp_liveshot \
    libchromatix_wayne_imx376_sunny_india_front_i_cpp_preview \
    libchromatix_wayne_imx376_sunny_india_front_i_cpp_snapshot \
    libchromatix_wayne_imx376_sunny_india_front_i_cpp_snapshot_5M \
    libchromatix_wayne_imx376_sunny_india_front_i_cpp_snapshot_5M_hht \
    libchromatix_wayne_imx376_sunny_india_front_i_cpp_snapshot_downscale \
    libchromatix_wayne_imx376_sunny_india_front_i_cpp_snapshot_hdr \
    libchromatix_wayne_imx376_sunny_india_front_i_cpp_snapshot_hht \
    libchromatix_wayne_imx376_sunny_india_front_i_cpp_snapshot_upscale \
    libchromatix_wayne_imx376_sunny_india_front_i_cpp_video \
    libchromatix_wayne_imx376_sunny_india_front_i_cpp_video_default \
    libchromatix_wayne_imx376_sunny_india_front_i_cpp_video_face \
    libchromatix_wayne_imx376_sunny_india_front_i_cpp_video_weixin \
    libchromatix_wayne_imx376_sunny_india_front_i_default_preview_3a \
    libchromatix_wayne_imx376_sunny_india_front_i_default_video_3a \
    libchromatix_wayne_imx376_sunny_india_front_i_face_video_3a \
    libchromatix_wayne_imx376_sunny_india_front_i_flash_cpp_liveshot \
    libchromatix_wayne_imx376_sunny_india_front_i_flash_cpp_preview \
    libchromatix_wayne_imx376_sunny_india_front_i_flash_cpp_snapshot \
    libchromatix_wayne_imx376_sunny_india_front_i_flash_cpp_video \
    libchromatix_wayne_imx376_sunny_india_front_i_flash_preview \
    libchromatix_wayne_imx376_sunny_india_front_i_flash_preview_3a \
    libchromatix_wayne_imx376_sunny_india_front_i_flash_snapshot \
    libchromatix_wayne_imx376_sunny_india_front_i_flash_video \
    libchromatix_wayne_imx376_sunny_india_front_i_flash_video_3a \
    libchromatix_wayne_imx376_sunny_india_front_i_fullsize_preview_3a \
    libchromatix_wayne_imx376_sunny_india_front_i_fullsize_video_3a \
    libchromatix_wayne_imx376_sunny_india_front_i_postproc \
    libchromatix_wayne_imx376_sunny_india_front_i_preview \
    libchromatix_wayne_imx376_sunny_india_front_i_snapshot \
    libchromatix_wayne_imx376_sunny_india_front_i_snapshot_hdr \
    libchromatix_wayne_imx376_sunny_india_front_i_video_default \
    libchromatix_wayne_imx376_sunny_india_front_i_video_face \
    libchromatix_wayne_imx376_sunny_india_front_i_video_weixin \
    libchromatix_wayne_imx376_sunny_india_front_i_weixin_video_3a \
    libchromatix_wayne_imx486_ofilm_cn_ii_4k_preview_3a \
    libchromatix_wayne_imx486_ofilm_cn_ii_4k_video_3a \
    libchromatix_wayne_imx486_ofilm_cn_ii_bokeh_preview \
    libchromatix_wayne_imx486_ofilm_cn_ii_bokeh_preview_3a \
    libchromatix_wayne_imx486_ofilm_cn_ii_common \
    libchromatix_wayne_imx486_ofilm_cn_ii_cpp_hfr_120 \
    libchromatix_wayne_imx486_ofilm_cn_ii_cpp_hfr_60 \
    libchromatix_wayne_imx486_ofilm_cn_ii_cpp_hfr_90 \
    libchromatix_wayne_imx486_ofilm_cn_ii_cpp_liveshot \
    libchromatix_wayne_imx486_ofilm_cn_ii_cpp_preview \
    libchromatix_wayne_imx486_ofilm_cn_ii_cpp_snapshot \
    libchromatix_wayne_imx486_ofilm_cn_ii_cpp_snapshot_bokeh \
    libchromatix_wayne_imx486_ofilm_cn_ii_cpp_snapshot_hdr \
    libchromatix_wayne_imx486_ofilm_cn_ii_cpp_snapshot_hht \
    libchromatix_wayne_imx486_ofilm_cn_ii_cpp_video \
    libchromatix_wayne_imx486_ofilm_cn_ii_cpp_video_4k \
    libchromatix_wayne_imx486_ofilm_cn_ii_cpp_video_weixin \
    libchromatix_wayne_imx486_ofilm_cn_ii_default_preview_3a \
    libchromatix_wayne_imx486_ofilm_cn_ii_default_video_3a \
    libchromatix_wayne_imx486_ofilm_cn_ii_hfr_120 \
    libchromatix_wayne_imx486_ofilm_cn_ii_hfr_120_3a \
    libchromatix_wayne_imx486_ofilm_cn_ii_hfr_60 \
    libchromatix_wayne_imx486_ofilm_cn_ii_hfr_60_3a \
    libchromatix_wayne_imx486_ofilm_cn_ii_hfr_90 \
    libchromatix_wayne_imx486_ofilm_cn_ii_hfr_90_3a \
    libchromatix_wayne_imx486_ofilm_cn_ii_pano_preview_3a \
    libchromatix_wayne_imx486_ofilm_cn_ii_postproc \
    libchromatix_wayne_imx486_ofilm_cn_ii_preview \
    libchromatix_wayne_imx486_ofilm_cn_ii_snapshot \
    libchromatix_wayne_imx486_ofilm_cn_ii_snapshot_hdr \
    libchromatix_wayne_imx486_ofilm_cn_ii_video \
    libchromatix_wayne_imx486_ofilm_cn_ii_video_4k \
    libchromatix_wayne_imx486_ofilm_cn_ii_video_weixin \
    libchromatix_wayne_imx486_ofilm_cn_ii_weixin_video_3a \
    libchromatix_wayne_imx486_ofilm_cn_ii_zsl_preview_3a \
    libchromatix_wayne_imx486_ofilm_cn_ii_zsl_video_3a \
    libchromatix_wayne_imx486_ofilm_india_ii_4k_preview_3a \
    libchromatix_wayne_imx486_ofilm_india_ii_4k_video_3a \
    libchromatix_wayne_imx486_ofilm_india_ii_bokeh_preview \
    libchromatix_wayne_imx486_ofilm_india_ii_bokeh_preview_3a \
    libchromatix_wayne_imx486_ofilm_india_ii_common \
    libchromatix_wayne_imx486_ofilm_india_ii_cpp_hfr_120 \
    libchromatix_wayne_imx486_ofilm_india_ii_cpp_hfr_60 \
    libchromatix_wayne_imx486_ofilm_india_ii_cpp_hfr_90 \
    libchromatix_wayne_imx486_ofilm_india_ii_cpp_liveshot \
    libchromatix_wayne_imx486_ofilm_india_ii_cpp_preview \
    libchromatix_wayne_imx486_ofilm_india_ii_cpp_snapshot \
    libchromatix_wayne_imx486_ofilm_india_ii_cpp_snapshot_bokeh \
    libchromatix_wayne_imx486_ofilm_india_ii_cpp_snapshot_hdr \
    libchromatix_wayne_imx486_ofilm_india_ii_cpp_snapshot_hht \
    libchromatix_wayne_imx486_ofilm_india_ii_cpp_video \
    libchromatix_wayne_imx486_ofilm_india_ii_cpp_video_4k \
    libchromatix_wayne_imx486_ofilm_india_ii_cpp_video_weixin \
    libchromatix_wayne_imx486_ofilm_india_ii_default_preview_3a \
    libchromatix_wayne_imx486_ofilm_india_ii_default_video_3a \
    libchromatix_wayne_imx486_ofilm_india_ii_hfr_120 \
    libchromatix_wayne_imx486_ofilm_india_ii_hfr_120_3a \
    libchromatix_wayne_imx486_ofilm_india_ii_hfr_60 \
    libchromatix_wayne_imx486_ofilm_india_ii_hfr_60_3a \
    libchromatix_wayne_imx486_ofilm_india_ii_hfr_90 \
    libchromatix_wayne_imx486_ofilm_india_ii_hfr_90_3a \
    libchromatix_wayne_imx486_ofilm_india_ii_pano_preview_3a \
    libchromatix_wayne_imx486_ofilm_india_ii_postproc \
    libchromatix_wayne_imx486_ofilm_india_ii_preview \
    libchromatix_wayne_imx486_ofilm_india_ii_snapshot \
    libchromatix_wayne_imx486_ofilm_india_ii_snapshot_hdr \
    libchromatix_wayne_imx486_ofilm_india_ii_video \
    libchromatix_wayne_imx486_ofilm_india_ii_video_4k \
    libchromatix_wayne_imx486_ofilm_india_ii_video_weixin \
    libchromatix_wayne_imx486_ofilm_india_ii_weixin_video_3a \
    libchromatix_wayne_imx486_ofilm_india_ii_zsl_preview_3a \
    libchromatix_wayne_imx486_ofilm_india_ii_zsl_video_3a \
    libchromatix_wayne_imx486_sunny_cn_i_4k_preview_3a \
    libchromatix_wayne_imx486_sunny_cn_i_4k_video_3a \
    libchromatix_wayne_imx486_sunny_cn_i_bokeh_preview \
    libchromatix_wayne_imx486_sunny_cn_i_bokeh_preview_3a \
    libchromatix_wayne_imx486_sunny_cn_i_common \
    libchromatix_wayne_imx486_sunny_cn_i_cpp_hfr_120 \
    libchromatix_wayne_imx486_sunny_cn_i_cpp_hfr_60 \
    libchromatix_wayne_imx486_sunny_cn_i_cpp_hfr_90 \
    libchromatix_wayne_imx486_sunny_cn_i_cpp_liveshot \
    libchromatix_wayne_imx486_sunny_cn_i_cpp_preview \
    libchromatix_wayne_imx486_sunny_cn_i_cpp_snapshot \
    libchromatix_wayne_imx486_sunny_cn_i_cpp_snapshot_bokeh \
    libchromatix_wayne_imx486_sunny_cn_i_cpp_snapshot_hdr \
    libchromatix_wayne_imx486_sunny_cn_i_cpp_snapshot_hht \
    libchromatix_wayne_imx486_sunny_cn_i_cpp_video \
    libchromatix_wayne_imx486_sunny_cn_i_cpp_video_4k \
    libchromatix_wayne_imx486_sunny_cn_i_cpp_video_weixin \
    libchromatix_wayne_imx486_sunny_cn_i_default_preview_3a \
    libchromatix_wayne_imx486_sunny_cn_i_default_video_3a \
    libchromatix_wayne_imx486_sunny_cn_i_hfr_120 \
    libchromatix_wayne_imx486_sunny_cn_i_hfr_120_3a \
    libchromatix_wayne_imx486_sunny_cn_i_hfr_60 \
    libchromatix_wayne_imx486_sunny_cn_i_hfr_60_3a \
    libchromatix_wayne_imx486_sunny_cn_i_hfr_90 \
    libchromatix_wayne_imx486_sunny_cn_i_hfr_90_3a \
    libchromatix_wayne_imx486_sunny_cn_i_pano_preview_3a \
    libchromatix_wayne_imx486_sunny_cn_i_postproc \
    libchromatix_wayne_imx486_sunny_cn_i_preview \
    libchromatix_wayne_imx486_sunny_cn_i_snapshot \
    libchromatix_wayne_imx486_sunny_cn_i_snapshot_hdr \
    libchromatix_wayne_imx486_sunny_cn_i_video \
    libchromatix_wayne_imx486_sunny_cn_i_video_4k \
    libchromatix_wayne_imx486_sunny_cn_i_video_weixin \
    libchromatix_wayne_imx486_sunny_cn_i_weixin_video_3a \
    libchromatix_wayne_imx486_sunny_cn_i_zsl_preview_3a \
    libchromatix_wayne_imx486_sunny_cn_i_zsl_video_3a \
    libchromatix_wayne_imx486_sunny_cn_iii_4k_preview_3a \
    libchromatix_wayne_imx486_sunny_cn_iii_4k_video_3a \
    libchromatix_wayne_imx486_sunny_cn_iii_bokeh_preview \
    libchromatix_wayne_imx486_sunny_cn_iii_bokeh_preview_3a \
    libchromatix_wayne_imx486_sunny_cn_iii_common \
    libchromatix_wayne_imx486_sunny_cn_iii_cpp_hfr_120 \
    libchromatix_wayne_imx486_sunny_cn_iii_cpp_hfr_60 \
    libchromatix_wayne_imx486_sunny_cn_iii_cpp_hfr_90 \
    libchromatix_wayne_imx486_sunny_cn_iii_cpp_liveshot \
    libchromatix_wayne_imx486_sunny_cn_iii_cpp_preview \
    libchromatix_wayne_imx486_sunny_cn_iii_cpp_snapshot \
    libchromatix_wayne_imx486_sunny_cn_iii_cpp_snapshot_bokeh \
    libchromatix_wayne_imx486_sunny_cn_iii_cpp_snapshot_hdr \
    libchromatix_wayne_imx486_sunny_cn_iii_cpp_snapshot_hht \
    libchromatix_wayne_imx486_sunny_cn_iii_cpp_video \
    libchromatix_wayne_imx486_sunny_cn_iii_cpp_video_4k \
    libchromatix_wayne_imx486_sunny_cn_iii_cpp_video_weixin \
    libchromatix_wayne_imx486_sunny_cn_iii_default_preview_3a \
    libchromatix_wayne_imx486_sunny_cn_iii_default_video_3a \
    libchromatix_wayne_imx486_sunny_cn_iii_hfr_120 \
    libchromatix_wayne_imx486_sunny_cn_iii_hfr_120_3a \
    libchromatix_wayne_imx486_sunny_cn_iii_hfr_60 \
    libchromatix_wayne_imx486_sunny_cn_iii_hfr_60_3a \
    libchromatix_wayne_imx486_sunny_cn_iii_hfr_90 \
    libchromatix_wayne_imx486_sunny_cn_iii_hfr_90_3a \
    libchromatix_wayne_imx486_sunny_cn_iii_pano_preview_3a \
    libchromatix_wayne_imx486_sunny_cn_iii_postproc \
    libchromatix_wayne_imx486_sunny_cn_iii_preview \
    libchromatix_wayne_imx486_sunny_cn_iii_snapshot \
    libchromatix_wayne_imx486_sunny_cn_iii_snapshot_hdr \
    libchromatix_wayne_imx486_sunny_cn_iii_video \
    libchromatix_wayne_imx486_sunny_cn_iii_video_4k \
    libchromatix_wayne_imx486_sunny_cn_iii_video_weixin \
    libchromatix_wayne_imx486_sunny_cn_iii_weixin_video_3a \
    libchromatix_wayne_imx486_sunny_cn_iii_zsl_preview_3a \
    libchromatix_wayne_imx486_sunny_cn_iii_zsl_video_3a \
    libchromatix_wayne_imx486_sunny_india_i_4k_preview_3a \
    libchromatix_wayne_imx486_sunny_india_i_4k_video_3a \
    libchromatix_wayne_imx486_sunny_india_i_bokeh_preview \
    libchromatix_wayne_imx486_sunny_india_i_bokeh_preview_3a \
    libchromatix_wayne_imx486_sunny_india_i_common \
    libchromatix_wayne_imx486_sunny_india_i_cpp_hfr_120 \
    libchromatix_wayne_imx486_sunny_india_i_cpp_hfr_60 \
    libchromatix_wayne_imx486_sunny_india_i_cpp_hfr_90 \
    libchromatix_wayne_imx486_sunny_india_i_cpp_liveshot \
    libchromatix_wayne_imx486_sunny_india_i_cpp_preview \
    libchromatix_wayne_imx486_sunny_india_i_cpp_snapshot \
    libchromatix_wayne_imx486_sunny_india_i_cpp_snapshot_bokeh \
    libchromatix_wayne_imx486_sunny_india_i_cpp_snapshot_hdr \
    libchromatix_wayne_imx486_sunny_india_i_cpp_snapshot_hht \
    libchromatix_wayne_imx486_sunny_india_i_cpp_video \
    libchromatix_wayne_imx486_sunny_india_i_cpp_video_4k \
    libchromatix_wayne_imx486_sunny_india_i_cpp_video_weixin \
    libchromatix_wayne_imx486_sunny_india_i_default_preview_3a \
    libchromatix_wayne_imx486_sunny_india_i_default_video_3a \
    libchromatix_wayne_imx486_sunny_india_i_hfr_120 \
    libchromatix_wayne_imx486_sunny_india_i_hfr_120_3a \
    libchromatix_wayne_imx486_sunny_india_i_hfr_60 \
    libchromatix_wayne_imx486_sunny_india_i_hfr_60_3a \
    libchromatix_wayne_imx486_sunny_india_i_hfr_90 \
    libchromatix_wayne_imx486_sunny_india_i_hfr_90_3a \
    libchromatix_wayne_imx486_sunny_india_i_pano_preview_3a \
    libchromatix_wayne_imx486_sunny_india_i_postproc \
    libchromatix_wayne_imx486_sunny_india_i_preview \
    libchromatix_wayne_imx486_sunny_india_i_snapshot \
    libchromatix_wayne_imx486_sunny_india_i_snapshot_hdr \
    libchromatix_wayne_imx486_sunny_india_i_video \
    libchromatix_wayne_imx486_sunny_india_i_video_4k \
    libchromatix_wayne_imx486_sunny_india_i_video_weixin \
    libchromatix_wayne_imx486_sunny_india_i_weixin_video_3a \
    libchromatix_wayne_imx486_sunny_india_i_zsl_preview_3a \
    libchromatix_wayne_imx486_sunny_india_i_zsl_video_3a \
    libchromatix_wayne_imx486_sunny_india_iii_4k_preview_3a \
    libchromatix_wayne_imx486_sunny_india_iii_4k_video_3a \
    libchromatix_wayne_imx486_sunny_india_iii_bokeh_preview \
    libchromatix_wayne_imx486_sunny_india_iii_bokeh_preview_3a \
    libchromatix_wayne_imx486_sunny_india_iii_common \
    libchromatix_wayne_imx486_sunny_india_iii_cpp_hfr_120 \
    libchromatix_wayne_imx486_sunny_india_iii_cpp_hfr_60 \
    libchromatix_wayne_imx486_sunny_india_iii_cpp_hfr_90 \
    libchromatix_wayne_imx486_sunny_india_iii_cpp_liveshot \
    libchromatix_wayne_imx486_sunny_india_iii_cpp_preview \
    libchromatix_wayne_imx486_sunny_india_iii_cpp_snapshot \
    libchromatix_wayne_imx486_sunny_india_iii_cpp_snapshot_bokeh \
    libchromatix_wayne_imx486_sunny_india_iii_cpp_snapshot_hdr \
    libchromatix_wayne_imx486_sunny_india_iii_cpp_snapshot_hht \
    libchromatix_wayne_imx486_sunny_india_iii_cpp_video \
    libchromatix_wayne_imx486_sunny_india_iii_cpp_video_4k \
    libchromatix_wayne_imx486_sunny_india_iii_cpp_video_weixin \
    libchromatix_wayne_imx486_sunny_india_iii_default_preview_3a \
    libchromatix_wayne_imx486_sunny_india_iii_default_video_3a \
    libchromatix_wayne_imx486_sunny_india_iii_hfr_120 \
    libchromatix_wayne_imx486_sunny_india_iii_hfr_120_3a \
    libchromatix_wayne_imx486_sunny_india_iii_hfr_60 \
    libchromatix_wayne_imx486_sunny_india_iii_hfr_60_3a \
    libchromatix_wayne_imx486_sunny_india_iii_hfr_90 \
    libchromatix_wayne_imx486_sunny_india_iii_hfr_90_3a \
    libchromatix_wayne_imx486_sunny_india_iii_pano_preview_3a \
    libchromatix_wayne_imx486_sunny_india_iii_postproc \
    libchromatix_wayne_imx486_sunny_india_iii_preview \
    libchromatix_wayne_imx486_sunny_india_iii_snapshot \
    libchromatix_wayne_imx486_sunny_india_iii_snapshot_hdr \
    libchromatix_wayne_imx486_sunny_india_iii_video \
    libchromatix_wayne_imx486_sunny_india_iii_video_4k \
    libchromatix_wayne_imx486_sunny_india_iii_video_weixin \
    libchromatix_wayne_imx486_sunny_india_iii_weixin_video_3a \
    libchromatix_wayne_imx486_sunny_india_iii_zsl_preview_3a \
    libchromatix_wayne_imx486_sunny_india_iii_zsl_video_3a \
    libdepthmapwrapper \
    libflash_pmic \
    libft2vendor \
    libhal_dbg \
    libjpegdhw \
    libjpegdmahw \
    libjpegehw \
    libmibokeh_660 \
    libmm-qcamera \
    libmmcamera2_c2d_module \
    libmmcamera2_cpp_module \
    libmmcamera2_iface_modules \
    libmmcamera2_imglib_modules \
    libmmcamera2_isp_modules \
    libmmcamera2_mct \
    libmmcamera2_mct_shimlayer \
    libmmcamera2_pp_buf_mgr \
    libmmcamera2_pproc_modules \
    libmmcamera2_sensor_modules \
    libmmcamera2_stats_modules \
    libmmcamera_arcsoftbokeh_lib \
    libmmcamera_bokeh \
    libmmcamera_depth_map \
    libmmcamera_eebinparse \
    libmmcamera_eeprom_util \
    libmmcamera_eztune_module \
    libmmcamera_facedetection_lib \
    libmmcamera_hdr_gb_lib \
    libmmcamera_hvx_add_constant \
    libmmcamera_hvx_grid_sum \
    libmmcamera_imglib \
    libmmcamera_imglib_faceproc_adspstub \
    libmmcamera_interface \
    libmmcamera_isp_abf48 \
    libmmcamera_isp_aec_bg_stats47 \
    libmmcamera_isp_bf_stats47 \
    libmmcamera_isp_bg_stats46 \
    libmmcamera_isp_bhist_stats44 \
    libmmcamera_isp_black_level48 \
    libmmcamera_isp_bpc48 \
    libmmcamera_isp_cac47 \
    libmmcamera_isp_chroma_enhan40 \
    libmmcamera_isp_chroma_suppress40 \
    libmmcamera_isp_clamp_encoder40 \
    libmmcamera_isp_clamp_video40 \
    libmmcamera_isp_clamp_viewfinder40 \
    libmmcamera_isp_color_correct46 \
    libmmcamera_isp_color_xform_encoder46 \
    libmmcamera_isp_color_xform_video46 \
    libmmcamera_isp_color_xform_viewfinder46 \
    libmmcamera_isp_cs_stats46 \
    libmmcamera_isp_demosaic48 \
    libmmcamera_isp_demux48 \
    libmmcamera_isp_fovcrop_encoder46 \
    libmmcamera_isp_fovcrop_video46 \
    libmmcamera_isp_fovcrop_viewfinder46 \
    libmmcamera_isp_gamma44 \
    libmmcamera_isp_gic48 \
    libmmcamera_isp_gtm46 \
    libmmcamera_isp_hdr48 \
    libmmcamera_isp_hdr_be_stats46 \
    libmmcamera_isp_hdr_bhist_stats44 \
    libmmcamera_isp_ihist_stats46 \
    libmmcamera_isp_linearization40 \
    libmmcamera_isp_ltm47 \
    libmmcamera_isp_luma_adaptation40 \
    libmmcamera_isp_mce40 \
    libmmcamera_isp_mesh_rolloff44 \
    libmmcamera_isp_pdaf48 \
    libmmcamera_isp_pedestal_correct46 \
    libmmcamera_isp_rs_stats46 \
    libmmcamera_isp_scaler_encoder46 \
    libmmcamera_isp_scaler_video46 \
    libmmcamera_isp_scaler_viewfinder46 \
    libmmcamera_isp_sce40 \
    libmmcamera_isp_snr47 \
    libmmcamera_isp_sub_module \
    libmmcamera_paaf_lib \
    libmmcamera_pdaf \
    libmmcamera_pdafcamif \
    libmmcamera_ppbase_module \
    libmmcamera_ppeiscore \
    libmmcamera_quadracfa \
    libmmcamera_sw2d_lib \
    libmmcamera_thread_services \
    libmmcamera_tuning \
    libmmcamera_tuning_lookup \
    libmmcamera_wayne_imx376_ofilm_back_ii \
    libmmcamera_wayne_imx376_ofilm_back_ii_eeprom \
    libmmcamera_wayne_imx376_ofilm_front_ii \
    libmmcamera_wayne_imx376_ofilm_front_ii_eeprom \
    libmmcamera_wayne_imx376_sunny_back_i \
    libmmcamera_wayne_imx376_sunny_back_i_eeprom \
    libmmcamera_wayne_imx376_sunny_back_iii \
    libmmcamera_wayne_imx376_sunny_back_iii_eeprom \
    libmmcamera_wayne_imx376_sunny_front_i \
    libmmcamera_wayne_imx376_sunny_front_i_eeprom \
    libmmcamera_wayne_imx486_ofilm_ii \
    libmmcamera_wayne_imx486_ofilm_ii_eeprom \
    libmmcamera_wayne_imx486_sunny_i \
    libmmcamera_wayne_imx486_sunny_i_eeprom \
    libmmcamera_wayne_imx486_sunny_iii \
    libmmcamera_wayne_imx486_sunny_iii_eeprom \
    libmmjpeg \
    libmmjpeg_interface \
    libmmlib2d_interface \
    libmmqjpeg_codec \
    libmmqjpegdma \
    libmpbase \
    libqomx_core \
    libqomx_jpegdec \
    libqomx_jpegenc \
    libqomx_jpegenc_pipe \
    libremosaic_daemon \
    libvidhance \
    libvidhance_gyro \
    libthermalfeature \
    libthermalioctl \
    cnss-daemon \
    android.hardware.gatekeeper@1.0-service-qti \
    android.hardware.keymaster@3.0-service-qti \
    sensors.qti \
    thermal-engine
